version: '3.8'

services:
  backend:
    build:
       context: .
       dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=notebook_user
      - POSTGRES_PASSWORD=notebook_password
      - POSTGRES_DB=notebook_db


volumes:
  postgres_data:
